### ISSUE TITLE
Many arguments not available 

### ISSUE THREAD

**Issue by devcose** [terra-farm/terraform-provider-xenorchestra#170]
Started using recently but have found many arguments are not available on the following versions maybe i'm missing something or putting them in the wrong places but i don't believe so 
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/terra-farm/xenorchestra v0.3.7

## wait_for_ip and ipv4_addresses return 
  
```
Error: Unsupported argument

   on main.tf line 84, in resource "xenorchestra_vm" "win10vm":
   84:     wait_for_ip = true

 An argument named "wait_for_ip" is not expected here.


 Error: Unsupported argument

   on main.tf line 85, in resource "xenorchestra_vm" "win10vm":
   85:     ipv4_addresses = "10.0.0.147/32"


 An argument named "ipv4_addresses" is not expected here. 
```

## as well accessing the majority of attributes 

`` output "server_public_ip" {
  value = xenorchestra_vm.win10vm.ipv4_addresses
}``

### returns 
``Error: Unsupported attribute
│
│   on main.tf line 104, in output "server_public_ip":
│  104:   value = xenorchestra_vm.win10vm.ipv4_addresses
│
│ This object has no argument, nested block, or exported attribute named "ipv4_addresses".``

If i'm missing something obvious please let me know otherwise is this just a version issue that i'm experiencing?

**Comment by ddelnano** [comment]
Hi @devcose, v0.3.7 is an extremely old version. The terraform registry docs are versioned and you can see from the screenshot below that v0.21.0 is the latest version. Please upgrade to the latest version and try again.

![Screen Shot 2021-11-04 at 4 41 54 AM](https://user-images.githubusercontent.com/5855593/140307752-b9aba679-fe06-4a6e-9da1-5a1948765f44.png)

I'm happy to continue providing support on this thread or in Discord, but I'll be closing this issue since I feel confident this is related to running an old version.
