### ISSUE TITLE
Error: malformed ws or wss URL

### ISSUE THREAD

**Issue by GilbertK99** [terra-farm/terraform-provider-xenorchestra#275]
Hello

I get this error below when i run terraform plan.

Planning failed. Terraform encountered an error while generating this plan.
 Error: malformed ws or wss URL
│
│   with provider["registry.terraform.io/terra-farm/xenorchestra"],
│   on providers.tf line 11, in provider "xenorchestra":
│   11: provider "xenorchestra" {
 

 This only happens when i use XOA_URL, XOA_USER and XOA_PASSWORD environment variables. When i replace the variables with the actual values eg. url = "wss://192.168.xx.xx" etc, the terraform plan works as expected.

This is my terraform code:

```
  # Instruct terraform to download the provider on `terraform init`
  terraform {
    required_providers {
      xenorchestra = {
        source = "terra-farm/xenorchestra"
      }
    }
  }

  # Configure the XenServer Provider
  provider "xenorchestra" {
    # Must be ws or wss
    url      = "XOA_URL"               # Or set XOA_URL environment variable
    username = "XOA_USER"              # Or set XOA_USER environment variable
    password = "XOA_PASSWORD"          # Or set XOA_PASSWORD environment variable

    # This is false by default and
    # will disable ssl verification if true.
    # This is useful if your deployment uses
    # a self signed certificate but should be
    # used sparingly!
    insecure = true              # Or set XOA_INSECURE environment variable to any value
  }

```

Any suggestions on what the issue could be?

**Comment by ddelnano** [comment]
@GilbertK99 the `url`, `username` and `password` HCL arguments should be omitted when you want it to fall back to the environment variables. They do not provide a way to tell terraform which environment variables to look at.

See that they are specified for each one: [url](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/490a0949c6c232758e5a560fb1298761d67bd8a6/xoa/provider.go#L27), [username](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/490a0949c6c232758e5a560fb1298761d67bd8a6/xoa/provider.go#L30), [password](https://github.com/terra-farm/terraform-provider-xenorchestra/blob/490a0949c6c232758e5a560fb1298761d67bd8a6/xoa/provider.go#L36).

Assuming the code you mentioned above is what you are testing with, this would be expected behavior (`XOA_URL` is not a valid websocket server address).

**Comment by GilbertK99** [comment]
Thank you so much! @ddelnano @ackjewtn I understand how its meant to work now.  My mistake was including the HCL arguments in the code.
VS Code kinda fooled me into thinking the attribute is required due to it showing some code errors as shown on this screenshot below.
![VSCode](https://github.com/terra-farm/terraform-provider-xenorchestra/assets/53891651/c6cf3ed0-dfc5-4d09-907a-a5050eb3d243)
