### ISSUE TITLE
vm does not get created get  jsonrpc2: code -32000

### ISSUE THREAD

**Issue by dc232** [terra-farm/terraform-provider-xenorchestra#61]
terraform version 
```
dc@ansible:~/xoa-terraform/terraform-xenserver$ terraform version
Terraform v0.13.2
+ provider registry.terraform.io/terra-farm/xenorchestra v0.3.7
```

terraform var file
```
variable "url_of_server" {
    type = string
    default = "ws://192.168.4.251"
}
```

terraform file
```
# Instruct terraform to download the provider on `terraform init`
terraform {
  required_providers {
    xenorchestra = {
      source = "terra-farm/xenorchestra"
      version = "~> 0.3.0"
    }
  }
}

# Configure the XenServer Provider
provider "xenorchestra" {
  # Must be ws or wss
  url      = var.url_of_server # Or set XOA_URL environment variable
  username = var.xen_username              # Or set XOA_USER environment variable
  password = var.xen_password            # Or set XOA_PASSWORD environment variable
}

data "xenorchestra_sr" "local_storage" {
    name_label = "Local storage"
}

data "xenorchestra_template" "template" {
  name_label = "Ubuntu Bionic Beaver 18.04"
}

data "xenorchestra_pif" "pif" {
  device = "eth0"
  vlan = -1
}

resource "xenorchestra_cloud_config" "base" {
  name = "cloudconfig"
  template = <<EOF
#cloud-init
tiemzone: America/New_York
hostname: terraformtest
package_update: true
package_upgrade: true
users:
  - name: test
    gecos: Test User
    groups: sudo
    passwd: test
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

network:
  version: 2
  ethernets:
    eno1:
      dhcp4: no
      addresses: [192.168.0.40/24]
      gateway4: 192.168.0.1
      nameservers:
         addresses: [192.168.0.1]

runcmd:
 - [ ls, -l, / ]
 - [ sh, -xc, "echo $(date) ': hello world!'" ]
 - [ sh, -c, echo "=========hello world'=========" ]
 - ls -l /root
EOF
}

resource "xenorchestra_vm" "base" {
    memory_max = 1073733632
    cpus  = 2
    cloud_config = xenorchestra_cloud_config.base.template
    name_label = "TerraformVM"
    name_description = "Created by Terraform Script"
    template = data.xenorchestra_template.template.id
    network {
	    network_id = data.xenorchestra_pif.pif.network
    }

    disk {
      sr_id = data.xenorchestra_sr.local_storage.id
      name_label = "Terraform_disk_imavo"
      size = 32212254720
    }
}
```

validation 
```
dc@ansible:~/xoa-terraform/terraform-xenserver$ terraform validate
Success! The configuration is valid.
```

error
``` 
dc@ansible:~/xoa-terraform/terraform-xenserver$ terraform apply test
xenorchestra_vm.base: Creating...

Error: jsonrpc2: code -32000 message: unknown error from the peer

  on server.tf line 65, in resource "xenorchestra_vm" "base":
  65: resource "xenorchestra_vm" "base" {

```
 form the logs in xoa
``` vm.create
{
  "CPUs": 2,
  "VIFs": [
    {
      "network": "bfb6ade5-124b-c710-b49c-d9f8e8ad4b44"
    }
  ],
  "bootAfterCreate": true,
  "cloudConfig": "#cloud-init\r\ntiemzone: America/New_York\r\nhostname: terraformtest\r\npackage_update: true\r\npackage_upgrade: true\r\nusers:\r\n  - name: test\r\n    gecos: Test User\r\n    groups: sudo\r\n    passwd: test\r\n    sudo: ['ALL=(ALL) NOPASSWD:ALL']\r\n\r\nnetwork:\r\n  version: 2\r\n  ethernets:\r\n    eno1:\r\n      dhcp4: no\r\n      addresses: [192.168.0.40/24]\r\n      gateway4: 192.168.0.1\r\n      nameservers:\r\n         addresses: [192.168.0.1]\r\n\r\nruncmd:\r\n - [ ls, -l, / ]\r\n - [ sh, -xc, \"echo $(date) ': hello world!'\" ]\r\n - [ sh, -c, echo \"=========hello world'=========\" ]\r\n - ls -l /root\r\n",
  "coreOs": false,
  "cpuCap": null,
  "cpuWeight": null,
  "existingDisks": {
    "0": {
      "$SR": "d7464b5d-660c-e013-2aa8-38f1eb1b6082",
      "name_label": "Terraform_disk_imavo",
      "size": 32212254720
    }
  },
  "memoryMax": 1073733632,
  "name_description": "Created by Terraform Script",
  "name_label": "TerraformVM",
  "template": "OpaqueRef:747790ba-f502-4ca8-bdcf-fbc1f2f6db81"
}
{
  "message": "no object with UUID or opaque ref: undefined",
  "name": "Error",
  "stack": "Error: no object with UUID or opaque ref: undefined
    at Xapi.apply (/usr/local/lib/node_modules/xo-server/node_modules/xen-api/src/index.js:601:11)
    at Xapi.getObject (/usr/local/lib/node_modules/xo-server/src/xapi/index.js:129:24)
    at Xapi.apply (/usr/local/lib/node_modules/xo-server/src/xapi/index.js:2370:21)
    at Xapi.createCloudInitConfigDrive (/usr/local/lib/node_modules/xo-server/node_modules/golike-defer/src/index.js:57:17)
    at Xapi.createVm (/usr/local/lib/node_modules/xo-server/src/xapi/mixins/vm.js:265:20)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at process.topLevelDomainCallback (domain.js:137:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/xo-server/src/api/vm.js:158:18)
    at Api.callApiMethod (/usr/local/lib/node_modules/xo-server/src/xo-mixins/api.js:301:20)"
}  
```
**Questions**
Question is why do I get for an undefined opaque via a data request? 
From what I can tell from the logs this parameter is defined?
Also, the vlan = -1  does this tell xcp to not tag the 802.1q frame?
Also there does not seem to be any mention in the https://github.com/terra-farm/terraform-provider-xenorchestra/blob/master/xoa/resource_xenorchestra_vm_test.go file to say how the system get the iso for the OS. 
So for example in vmware you can specify that the ubuntu iso is in the datastore how does xcp get this information?

**Comment by dc232** [comment]
Did a bit more debugging and i think this is a result of the template UUIDs being incorrect which is bizarre given its a data element, so its meant to be coming as a value from xoa

Anyway turns out the template UUID exspected value is meant to return in my case
74ae424d-a1d3-4d96-9827-d1d60a4c7511

the actual value appears to be 
747790ba-f502-4ca8-bdcf-fbc1f2f6db81

unless OpaqueRef and UUID are two completely  different objects?

I'll test this theory and  report back

**Comment by dc232** [comment]
turns out i was mistaken 
``` 
Error: jsonrpc2: code 1 message: no such VM-template OpaqueRef:74ae424d-a1d3-4d96-9827-d1d60a4c7511: {"id":"OpaqueRef:74ae424d-a1d3-4d96-9827-d1d60a4c7511","type":"VM-template"}

  on server.tf line 65, in resource "xenorchestra_vm" "base":
  65: resource "xenorchestra_vm" "base" {
```

**Comment by dc232** [comment]
well im stumped just the id through the xo-cli and it reports correct no idea what the UUID error is on about OpaqueRef:747790ba-f502-4ca8-bdcf-fbc1f2f6db81

**Comment by ddelnano** [comment]
Hi @dc232, thanks for giving the provider a try!

>  Also there does not seem to be any mention in the https://github.com/terra-farm/terraform-provider-xenorchestra/blob/master/xoa/resource_xenorchestra_vm_test.go file to say how the system get the iso for the OS.

The reason ISOs can't be specified is because the provider is expecting you to pass a VM template that has a disk with an OS already installed. This is also why you are seeing the `no object with UUID or opaque ref: undefined` error. Basically the template you are using is not compatible with the underlying api call the provider makes.

In order to create a working template you will need to do the following:
1. Use the XO web UI to create a VM from a template
2. Insert the ISO you want to the VM
3. Start the VM and install the OS
4. Create a new template from that VM

The resulting template will be compatible with the `xenorchestra_vm` resource and is how I've been using the provider. The documentation could be more clear on this and it's a common issue others have ran into (#39 is the github issue for the other recent occurrence).

I have a few ideas on how to improve this experience:
1. Making the documentation better so it's obvious how the template parameter should be used
2. Having the terraform provider detect this situation and refuse to create the VM with a helpful error message

Eventually I would like to have the provider work with ISOs but I would likely invest time in resurrecting [this project](https://github.com/xenserver/packer-builder-xenserver) (or a creating new derivative based on the XO api) first. Packer is another hasicorp tool that allows you to codify your OS images and would produce a template that is compatible with the `xenorchestra_vm` resource.

Since there is already an issue for this I'm going to close this as a duplicate. You can follow along #39 if you want to know when ISOs are supported or you can use the procedure I outlined above to create a template that will work.

I'm also more than happy to continue troubleshooting using the provider here or on Discord :)

**Comment by dc232** [comment]
Hi @ddelnano thanks for the speedy reply, what's the discord link? I'm keen to have more of a look at the terraform provider, I also wanted to understand if there is a way to adding tagging to the bonded network interface at the mo it looks like xcp accepts only untagged frames when using VM's

**Comment by ddelnano** [comment]
The discord link is in the README. The tagging piece I'm not quite sure so maybe we can continue that chat there?
